#!/usr/bin/env php
<?php

/**
 * Gizmo Console Application
 *
 * @author  Olaf Luijks
 * @version 0.0.2
 */

// passthru('clear');

require __DIR__.'/vendor/autoload.php';

use Gizmo\Console\Commands\ConfigCommand;
use Gizmo\Console\Commands\Database\MySQL\DumpCommand;
use Gizmo\Console\Commands\Database\MySQL\ListsDatabasesCommand;
use Gizmo\Console\Commands\PHP\RestartPhp5Command;
use Gizmo\Console\Commands\Webserver\Nginx\RestartNginxCommand;
use Gizmo\Console\Commands\Server\ServerHealthCheckCommand;
use Gizmo\Console\Commands\UpdateCommand;

use Symfony\Component\Console\Application;

$gizmo = new Application('Gizmo Console Application', '0.0.2');
// Config commands
$gizmo->add(new ConfigCommand());
// Mysql commands
$gizmo->add(new DumpCommand());
$gizmo->add(new ListsDatabasesCommand());
// Php5 commands
$gizmo->add(new RestartPhp5Command());
// Nginx commands
$gizmo->add(new RestartNginxCommand());
// Server commands
$gizmo->add(new ServerHealthCheckCommand());
// Gizmo commands
$gizmo->add(new UpdateCommand());
// Run this baby
$gizmo->run();
