#!/usr/bin/env php
<?php

/**
 * Gizmo Console Application
 *
 * @author  Olaf Luijks
 * @version 1.0.9
 *
 * Copyright 2015 Olaf Luijks
 * Licensed under the MIT license
 * @link https://github.com/oluijks/gizmo/blob/master/LICENSE
 */

// passthru('clear');

require __DIR__.'/vendor/autoload.php';

use Gizmo\Console\Commands\ConfigCommand;
use Gizmo\Console\Commands\Database\MySQL\DatabaseDumpCommand;
use Gizmo\Console\Commands\Database\MySQL\ListsDatabasesCommand;
use Gizmo\Console\Commands\Downloads\DownloadWordPressCommand;
use Gizmo\Console\Commands\Downloads\DownloadMagento2Command;
use Gizmo\Console\Commands\Webserver\MakeNginxVhostCommand;
use Gizmo\Console\Commands\Webserver\RestartPhp5Command;
use Gizmo\Console\Commands\Webserver\RestartNginxCommand;
use Gizmo\Console\Commands\Webserver\RestartMySqlCommand;
use Gizmo\Console\Commands\Webserver\WebserverStatusCommand;
use Gizmo\Console\Commands\AboutCommand;
use Gizmo\Console\Commands\MakeCommand;
use Gizmo\Console\Commands\UpdateCommand;

use Symfony\Component\Console\Application;

$gizmo = new Application('Gizmo Console Application', '@package_version@');
// Database commands
$gizmo->add(new DatabaseDumpCommand());
$gizmo->add(new ListsDatabasesCommand());
// Downloads commands
$gizmo->add(new DownloadWordPressCommand());
$gizmo->add(new DownloadMagento2Command());
// Webserver commands
$gizmo->add(new MakeNginxVhostCommand());
$gizmo->add(new WebserverStatusCommand());
$gizmo->add(new RestartNginxCommand());
$gizmo->add(new RestartPhp5Command());
$gizmo->add(new RestartMySqlCommand());
// Gizmo commands
$gizmo->add(new AboutCommand());
$gizmo->add(new MakeCommand());
$gizmo->add(new UpdateCommand());
// Run baby
$gizmo->run();
